server.port: 8085
spring:
  application.name: spring-jackson     
  jackson:
    serialization: 
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    locale: pt_BR
    time-zone: GMT-03:00
    date-format: yyyy-MM-dd HH:mm:ss
