jwt:
  expiration: 604800
  secret: permasolutionsecretpermasolutionsecretpermasolutionsecretpermasolutionsecret
  #header: token
  #route.authentication.path: /auth
  #route.authentication.refresh: /refresh
